name: spring

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  build:
    env:
      workdir: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 자바 17 버전으로 설정
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17 
          distribution: 'adopt'

      # application.properties 파일 생성
      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash
        working-directory: ${{ env.workdir }}
      
      # gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ env.workdir }}

      # 도커 이미지 빌드, 푸시
      # 도커 이미지 빌드는 dockerfile을 사용
      - name: Build and push Docker images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker build -t ${{ secrets.DOCKER_REPO }}:backend .
          docker push ${{ secrets.DOCKER_REPO }}:backend
        working-directory: ${{ env.workdir }}
      
      # 서버에 접속, 스크립트 실행
      - name: SSH and run scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/projec0:backend
            docker compose down
            docker compose up -d